@echo off
echo Syncing SLS docs from vault...
xcopy "G:\My Drive\vault\02-SLS\*.md" "C:\Users\Caleb\sls-project\docs\" /Y /S /Q
echo Done. Launching Claude Code...
cd /d C:\Users\Caleb\sls-project
claude
